### ISSUE TITLE
Upcoming removal of function used in public_key - ssh_decode

### ISSUE THREAD

**Issue by bahner** [jbenden/esshd#10]
warning: :public_key.ssh_decode/2 is deprecated. It will be removed in OTP 26. Use ssh_file:decode/2 instead
  lib/esshd/public_key_authenticator.ex:143: Sshd.PublicKeyAuthenticator.AuthorizedKeys.ssh_decode_line/2

**Comment by jbenden** [comment]
Thanks for the info! Hopefully I can get to this reasonably soon.

PS: Patches are always welcomed, too! :)

-Joe

**Comment by jbenden** [comment]
Version 0.3.0 will have this change included.
