### ISSUE TITLE
access_list only applies to password authentication

### ISSUE THREAD

**Issue by EvelynSubarrow** [jbenden/esshd#12]
I'm not sure if this could exactly be considered to be a bug, but I was a bit surprised when I discovered through experimentation that access_list only applied to password authentication and not key authentication. I've been reading through :ssh docs and comparing them to esshd's source code and I now understand _why_ this is the case, but either way, unpleasant surprises for security-related features are not a great thing to have.

So, my proposal is either to change the behaviour to be more in line with what someone might expect (i.e. access_list is used to filter all incoming connections), or to change the documentation to make the behaviour clearer

**Comment by jbenden** [comment]
This project really only wraps functionality provided by Erlang. So it should honestly be fully fixed in this location; but baring that then a documentation change may be in order. Sad, yes. Though the SSH functionality in Erlang seems more for debugging stuff and not anywhere near a full production SSH.

**Comment by EvelynSubarrow** [comment]
Agreed, it's frustrating that Erlang's SSH tools are in the state they are, extremely promising but there's lots of little inconsistencies like these. I'd say my recommendation would be to add a short note in esshd which explains the limitations of access_list, I'd be happy to make a small MR if you'd like

**Comment by jbenden** [comment]
Either is acceptable, but you seem eager! :)

**Comment by EvelynSubarrow** [comment]
Sorry for the wait, I've submitted a MR! Feel free to leave comments if you want the wording changed

**Comment by jbenden** [comment]
Sorry on my delay, too! :)

Thanks for everything!
-Joe
