### ISSUE TITLE
except raised once connected with password login

### ISSUE THREAD

**Issue by shifters67** [jbenden/esshd#2]
Apologies if i am doing something stupid but ...

I get the following error in the iex shell when attempting to login i.e. i can connect ok as below

SSH server
Enter password for "tests"
password: testpass

From iex:

10:32:45.214 [warn]  Exception caught
10:32:45.214 [error] Error in process #PID<0.410.0> on node :"test@twri-AX370-Gaming-K3.home.org" with exit value:
{{:badmatch, {:error, :terminated}}, [{IEx, :"-start/2-fun-0-", 2, [file: 'lib/iex.ex', line: 744]}]}

With config:

config :esshd,
    enabled: true,
    priv_dir: File.cwd! <> "/priv/",
    handler: "Sshd.ShellHandler.Elixir",
    port: 10_022,
    password_authenticator: "Sshd.PasswordAuthenticator.Test"
  
I have tried logging in with keys and your standard config previously and although i have followed and created the keys etc i am ALWAYS asked for pasword (even though i did return in the key generation stage) hence why trying to login with password.

This is on ubuntu 18.04 with elixir 1.6.6 and Erlang 20.1.3

Any help appreciated!

**Comment by shifters67** [comment]
connect successfully while using shell of  Sshd.ShellHandler.Example and password login

**Comment by jeanparpaillon** [comment]
Same issue here, with authorized_keys method. Tracing the calls, this crash happens when spawning shell, so nothing related to authentication.
Nevertheless, both Erlang and Elixir shells crashes

Elixir: 1.7.4
Erlang: 21.2.4

**Comment by jeanparpaillon** [comment]
In `Sshd.Server`, replacing `shell` option in `ssh.daemon/2` function with `{IEx, :start, []}` or `{:shell, :start, []}` fix the issue
